// FrontendDevelopment/HandsOn9/student-portal-vue/src/components/CourseCard.vue
<template>
  <div class="card">
    <h3>{{ name }}</h3>
    <p><strong>Code:</strong> {{ code }}</p>
    <p><strong>Credits:</strong> {{ credits }}</p>
    <p><strong>Grade:</strong> {{ grade }}</p>
  </div>
</template>

<script setup>
defineProps({
  name: String,
  code: String,
  credits: Number,
  grade: String
})
</script>

<style scoped>
.card{
    border:1px solid gray;
    padding:15px;
    margin:10px;
    border-radius:8px;
}
</style>

// FrontendDevelopment/HandsOn5/student-portal-react/src/components/CourseCard.jsx
function CourseCard(props) {
  return (
    <div
      style={{
        border: "1px solid gray",
        borderRadius: "8px",
        padding: "15px",
        margin: "20px 0",
        width: "300px",
        backgroundColor: "#ffffff"
      }}
    >
      <h2>{props.name}</h2>

      <p><strong>Code:</strong> {props.code}</p>

      <p><strong>Credits:</strong> {props.credits}</p>

      <p><strong>Grade:</strong> {props.grade}</p>
    </div>
  );
}

export default CourseCard;
