// FrontendDevelopment/HandsOn8/student-portal-vue/src/components/Header.vue
<template>

<nav>

<RouterLink to="/">Home</RouterLink>

|

<RouterLink to="/courses">Courses</RouterLink>

|

<RouterLink to="/profile">Profile</RouterLink>

|

<b>Enrolled:</b> {{ store.enrolledCourses.length }}

</nav>

<hr>

</template>

<script setup>

import { RouterLink } from 'vue-router'
import { useEnrollmentStore } from '../stores/enrollment'

Enrolled: {{ store.enrolledCourses.length }}

const store = useEnrollmentStore()

</script>

// FrontendDevelopment/HandsOn6/student-portal-router/src/components/Header.jsx
import { Link } from "react-router-dom";
import { useSelector } from "react-redux";

function Header() {

  const enrolledCourses = useSelector(
    (state) => state.enrollment.enrolledCourses
  );

  return (
    <header>
      <h1>Student Portal</h1>

      <nav>
        <Link to="/">Home</Link>{" | "}
        <Link to="/courses">Courses</Link>{" | "}
        <Link to="/profile">Profile</Link>
      </nav>

      <p>
        <strong>Enrolled Courses:</strong>{" "}
        {enrolledCourses.length}
      </p>

      <hr />
    </header>
  );
}

export default Header;
