// FrontendDevelopment/HandsOn5/student-portal-react/src/components/Header.jsx
function Header(props) {
  return (
    <header>
      <h1>{props.siteName}</h1>

      <nav>
        <a href="#">Home</a> |{" "}
        <a href="#">Courses</a> |{" "}
        <a href="#">Profile</a>
      </nav>

      <p>
        <strong>Enrolled Courses:</strong> {props.enrolledCount}
      </p>

      <hr />
    </header>
  );
}

export default Header;

// FrontendDevelopment/HandsOn8/student-portal-vue/src/components/Header.vue
<template>

<nav>

<RouterLink to="/">Home</RouterLink>

|

<RouterLink to="/courses">Courses</RouterLink>

|

<RouterLink to="/profile">Profile</RouterLink>

|

<b>Enrolled:</b> {{ store.enrolledCourses.length }}

</nav>

<hr>

</template>

<script setup>

import { RouterLink } from 'vue-router'
import { useEnrollmentStore } from '../stores/enrollment'

Enrolled: {{ store.enrolledCourses.length }}

const store = useEnrollmentStore()

</script>
